seed: 256
dataset:
  train:
    params:
      batch_size: 1024
      num_workers: 64
      shuffle: True
    transform:
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.49139968
        - 0.48215827
        - 0.44653124
        std:
        - 0.24703233
        - 0.24348505
        - 0.26158768
  validation:
    params:
      batch_size: 1024
      num_workers: 64
      shuffle: True
    transform:
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.49139968
        - 0.48215827
        - 0.44653124
        std:
        - 0.24703233
        - 0.24348505
        - 0.26158768
  test:
    params:
      batch_size: 1
      num_workers: 1
      shuffle: True
    transform:
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.49139968
        - 0.48215827
        - 0.44653124
        std:
        - 0.24703233
        - 0.24348505
        - 0.26158768
general:
  class_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 30
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.0001
        weight_decay: 0.0005
    epochs: 90
  grouping_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    grouping_volatility: 1.02
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 30
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.0001
        weight_decay: 0.0005
    epochs: 90