dataset:
  train:
    params:
      batch_size: 16
      num_workers: 2
      shuffle: True
    transform:
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.500
        - 0.500
        - 0.500
        std:
        - 0.500
        - 0.500
        - 0.500
  validation:
    params:
      batch_size: 16
      num_workers: 2
      shuffle: True
    transform:
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.500
        - 0.500
        - 0.500
        std:
        - 0.500
        - 0.500
        - 0.500
  test:
    params:
      batch_size: 1
      num_workers: 2
      shuffle: True
hyperparameters:
  learning_rate: 0.0001
  lr_scheduler: 
  - type: CosineAnnealingLR
    params:
      T_max: 10
      eta_min: 0
  weight_decay: 0.0005
  epochs: 20
  grouping_volatility: 0.70
  descendant_learning_rate: 0.005
  descendant_weight_decay: 0.0005
  descendant_epochs: 20
retrain: