seed: 42
dataset:
  train:
    params:
      batch_size: 32
      num_workers: 2
      shuffle: True
    transform:
    - type: RandomCrop
      params:
        size:
        - 32
        - 32
        padding: 4
    - type: Resize
      params:
        size:
        - 224
        - 224
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.500
        - 0.500
        - 0.500
        std:
        - 0.500
        - 0.500
        - 0.500
  validation:
    params:
      batch_size: 32
      num_workers: 2
      shuffle: True
    transform:
    - type: RandomCrop
      params:
        size:
        - 32
        - 32
        padding: 4
    - type: Resize
      params:
        size:
        - 224
        - 224
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.500
        - 0.500
        - 0.500
        std:
        - 0.500
        - 0.500
        - 0.500
  test:
    params:
      batch_size: 1
      num_workers: 2
      shuffle: True
general:
  class_hyperparameters:
    loss: 
    - type: NLLLoss
    lr_scheduler: 
    - type: CosineAnnealingLR
      params:
        T_max: 10
        eta_min: 0
    optimizer: 
    - type: Adam
      params:
        lr: 0.001
        weight_decay: 0.0005
    epochs: 40
  grouping_hyperparameters:
    loss: 
    - type: NLLLoss
    grouping_volatility: 0.70
    lr_scheduler: 
    - type: CosineAnnealingLR
      params:
        T_max: 10
        eta_min: 0
    optimizer: 
    - type: Adam
      params:
        lr: 0.0001
        weight_decay: 0.0005
    epochs: 40