seed: 42
dataset:
  train:
    params:
      batch_size: 256
      num_workers: 64
      shuffle: True
    transform:
    - type: ToTensor
  validation:
    params:
      batch_size: 256
      num_workers: 64
      shuffle: True
    transform:
    - type: ToTensor
  test:
    params:
      batch_size: 1
      num_workers: 2
      shuffle: True
general:
  class_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 30
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.001
        weight_decay: 0.0005
    epochs: 90
  grouping_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    grouping_volatility: 0.70
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 30
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.001
        weight_decay: 0.0005
    epochs: 90